-- =====================================================================
-- Pact. — Allow uploading your own contract PDF
--
-- Phase 4f: contracts can either be generated by Pact's structured form
-- (existing flow) or uploaded as a PDF. Uploaded contracts skip the
-- contract_sections / technical_requirements / hospitality_requirements /
-- additional_terms fields entirely.
-- =====================================================================

create type contract_source as enum ('generated', 'uploaded');

alter table contracts
  add column if not exists source contract_source not null default 'generated',
  add column if not exists uploaded_file_path text,
  add column if not exists uploaded_file_name text;

-- Storage bucket for uploaded contracts. Private — never publicly readable;
-- access is mediated by the getContractFileUrl edge function which checks
-- the caller is a party to the contract and returns a short-lived signed URL.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'contract-uploads',
  'contract-uploads',
  false,
  20971520,  -- 20 MB
  array['application/pdf']::text[]
)
on conflict (id) do update set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types,
  public = excluded.public;

-- Storage RLS: an authenticated user may upload to a path that begins with
-- a contract_id where they are either the contractor or the client.
-- Path convention: {contract_id}/{filename}.
create policy "contract parties can upload"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'contract-uploads'
    and exists (
      select 1
      from contracts c
      join profiles p on p.id in (c.contractor_profile_id, c.client_profile_id)
      where c.id::text = (storage.foldername(name))[1]
        and p.user_id = auth.uid()
    )
  );

create policy "contract parties can read uploads"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'contract-uploads'
    and exists (
      select 1
      from contracts c
      join profiles p on p.id in (c.contractor_profile_id, c.client_profile_id)
      where c.id::text = (storage.foldername(name))[1]
        and p.user_id = auth.uid()
    )
  );

create policy "contract parties can delete uploads"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'contract-uploads'
    and exists (
      select 1
      from contracts c
      join profiles p on p.id in (c.contractor_profile_id, c.client_profile_id)
      where c.id::text = (storage.foldername(name))[1]
        and p.user_id = auth.uid()
    )
  );
